# -*- coding: utf-8 -*-
"""Jeffery-Data Analysis Project Oct 2023

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqKzvO0w9I7M7fzdXCHNJSpHLmTwDLBF

#1 - Data Loading and inspection
"""

#importing everything

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#gets the data and assigns it as 'URL' then makes a dataframe

URL = "https://raw.githubusercontent.com/Jeffery2k5/R6Data/main/operators.csv"
df = pd.read_csv(URL)
df = pd.DataFrame(df)
df

"""##Basic information"""

#top of data frame
df.head()

#Bottom of data frame

df.tail()

#Shape of data frame / number of rows and columns

print(df.shape)

#Gets the info of data frame

df.info()

"""#Missing Values"""

#non updated values / Before

df.isnull().sum()

#updates the values

df = df.fillna("NO OPTION")

#updated values / After

df.isnull().sum()

#show updated values
df.head()

"""#2 - Data Cleaning"""

#corrects the incorrect value in organization for GSG9 , originally 'GSG9' - 'GSG12' when it should only be 'GSG9'
df.loc[42:45,['Organization']] = 'GSG9'
df.tail(12)

#Deletes the columns 'Gadget1' and 'Gadget2' as they will not be used
df = df.drop(['Gadget1', 'Gadget2'], axis=1)
df.tail(12)

"""#3 - Descriptive statistics"""

#gets the mean
df.mean()

#gets the mean for just Defenders through a process that shows step by step
#creates defenders data frame
Defenders = df[df['Role'] == 'DEFENDER']

#resets the index
Defenders = Defenders.reset_index(drop=True)

#shows defenders mean()
Defenders.mean()

#gets the mean for just Attackers through a simpler process
#creates the attackers data frame and resets the index
Attackers = df[df['Role'] == 'ATTACKER'].reset_index(drop=True)

#displays the attackers mean()
Attackers.mean()

#gets the mdeian
df.median()

#gets mode but removes the nan values it creates to make it look beter
#While name does not have any duplicates it chooses 'ALIBI' due to alphabetical order , same is applied for attacker as it is even with 'DEFENDER'
df.mode().dropna()

#Standard Deviation of data frame

df.std()

#Describes the data frame

df.describe()

"""#4 - Data Visualization / Relationship between variables

#Stats Display
"""

#Displays all comparison stats
#creates a 2x2 instead of a 3x1 since a 3x1 just looked weird

#creates a plot that compares the Armor by Role at position 1 , 1
plt.subplot(2, 2, 1)
sns.countplot(x = "Armor", hue = df["Role"], data = df ,palette = "rocket")

#creates a plot that compares the Speed by Role at position 1 , 2
plt.subplot(2, 2, 2)
sns.countplot(x = "Speed", hue = df["Role"], data = df ,palette = "mako")

#creates a plot that compares the Difficulty by Role at position 2 , 1
plt.subplot(2, 2, 3)
sns.countplot(x = "Difficulty", hue = df["Role"], data = df ,palette = "pastel")

#tight_layout makes sure they do not overlap
plt.tight_layout()

#displays
plt.show()

"""##Armor"""

#creates a 2x1 grid for plotting the graphs
#creates a plot at position 1 , 1
plt.subplot(1, 2, 1)


#creates the graph that shows the overall Armor
sns.countplot(x = "Armor", data = df ,palette = "rocket")

#sets the size
plt.gcf().set_size_inches(8,5)

#creates the titles and labels
plt.title("Average Total Armor")
plt.ylabel("Amount of Operators")
plt.xlabel("Armor amount")

#creates a plot at position 1 , 2
plt.subplot(1, 2, 2)

#creates the graph that shows the comparison by the roles
sns.countplot(x = "Armor", hue = df["Role"], data = df ,palette = "rocket")

#sets the size
plt.gcf().set_size_inches(8,5)

#creates the titles and labels
plt.title("Average Armor Compared By Role")
plt.ylabel("Amount of Operators")
plt.xlabel("Armor amount")

#tight_layout makes sure they do not overlap
plt.tight_layout()

#displays
plt.show()

df[df["Armor"] == 3]

"""#Speed"""

#creates a 2x1 grid for plotting the graphs
#creates a plot at position 1 , 1
plt.subplot(1, 2, 1)

#creates the graph that shows the overall Speed
sns.countplot(x = "Speed", data = df ,palette = "mako")

#sets the size
plt.gcf().set_size_inches(8,5)

#creates the titles and labels
plt.title("Average Total Speed")
plt.ylabel("Amount of Operators")
plt.xlabel("Speed amount")

#creates a plot at position 1 , 2
plt.subplot(1, 2, 2)

#creates the graph that shows the comparison by the roles
sns.countplot(x = "Speed", hue = df["Role"], data = df ,palette = "mako")

#sets the size
plt.gcf().set_size_inches(8,5)

#creates the titles and labels
plt.title("Average Speed Compared By Role")
plt.ylabel("Amount of Operators")
plt.xlabel("Speed amount")

#tight_layout makes sure they do not overlap
plt.tight_layout()

#displays
plt.show()

df[df["Speed"] == 3]

"""#Difficulty

Since this is a 'competative' video game they try to balance each side so sometimes data like this exist where both sides are considered equally difficult
"""

#creates a 2x1 grid for plotting the graphs
#creates a plot at position 1 , 1
plt.subplot(1, 2, 1)

#creates the graph that shows the overall Difficulty
sns.countplot(x = "Difficulty", data = df ,palette = "pastel")

#sets the size
plt.gcf().set_size_inches(8,5)

#creates the titles and labels
plt.title("Average Total Difficulty")
plt.ylabel("Amount of Operators")
plt.xlabel("Difficulty amount")


#creates a plot at position 1 , 2
plt.subplot(1, 2, 2)

#creates the graph that shows the comparison by the roles
sns.countplot(x = "Difficulty", hue = df["Role"], data = df ,palette = "pastel")

#sets the size
plt.gcf().set_size_inches(8,5)

#creates the titles and labels
plt.title("Average Difficulty per Role")
plt.ylabel("Amount of Operators")
plt.xlabel("Difficulty amount")

#tight_layout makes sure they do not overlap
plt.tight_layout()

#displays
plt.show()

df[df["Difficulty"] == 3]

"""##Heatmap"""

#hmDf stands for heatmap dataframe , this will be used instead of df so the changes to index to change df index
#hm stands for heatmap

#makes the figure size
plt.figure(figsize=(12, 12))

#creates a new data frame from df
hmDf = df

#changes the index to 'Name'
hmDf = hmDf.set_index('Name')

#The heatmap graph
hm = sns.heatmap(data = hmDf[['Armor', 'Speed','Difficulty']],linewidths=2, linecolor='black', cmap = "YlOrBr",vmin=1, vmax = 3)

"""#New Column that tells if a character is begginer friendly"""

#This creates a new column based on the data in column "Difficulty"

#assigns the variable 'beginner'
beginner  = df['Difficulty']

#my function to go through and assign the column value.    [1 is Yes]    [2 is Kinda]    [3 is No]
def Beginner_Friendly(beginner):
    if beginner == 1:
        return "Yes"
    elif beginner == 2:
        return "Kinda"
    elif beginner == 3:
        return "No"

#creates the new column called 'Beginner Friendly'
df['Beginner Friendly'] = beginner.map(Beginner_Friendly)

#Displays df so I can see if it worked
df.head(7)

"""#Finds all beginner friendly operators"""

#Creates a new dataframe based off the column 'Beginner Friendly' inorder to make code simplier in the future
BeginnerFriendly = df[df["Beginner Friendly"] == "Yes"]

#Resets Index , it is seperate from the first so the steps can be seen and followed
BeginnerFriendly = BeginnerFriendly.reset_index(drop=True)

#Displays BeginnerFriendly
BeginnerFriendly

#Same result can be accomplished with the line of code below but would not create a new dataframe nor change df
#df[df["Beginner Friendly"] == "Yes"].reset_index(drop=True)

#information to analyize about beginner friendly
#creates a plot at position 1, 1
plt.subplot(1, 2, 1)
sns.countplot(x = "Armor", data = BeginnerFriendly ,palette = "rocket")

#creates a plot at position 1, 2
plt.subplot(1, 2, 2)
sns.countplot(x = "Speed", data = BeginnerFriendly ,palette = "mako")

#prints some data information from beginner friendly
print("The average total of armor and speed together for Beginner Friendly", BeginnerFriendly['Armor'].mean() + BeginnerFriendly['Speed'].mean())
print("The average armor for Beginner Friendly",BeginnerFriendly['Armor'].mean())
print("The average speed for Beginner Friendly",BeginnerFriendly['Speed'].mean())

"""#Beginner Friendly Attackers"""

#Shows attackers who are beginner friendly , can be assigned to new data frame if wanted to be used in the future
BeginnerFriendly[BeginnerFriendly["Role"] == "ATTACKER"].reset_index(drop=True)

"""#Beginner Friendly Defenders"""

#Shows Defenders who are beginner friendly
BeginnerFriendly[BeginnerFriendly["Role"] == "DEFENDER"].reset_index(drop=True)

"""#Beginner friendly with 3 Armor"""

#Shows beginner friendly operators who have 3 Armor
BeginnerFriendly[BeginnerFriendly["Armor"] == 3].reset_index(drop=True)

"""#Beginner friendly with 3 Speed"""

#Shows beginner friendly operators who have 3 Speed
BeginnerFriendly[BeginnerFriendly["Speed"] == 3].reset_index(drop=True)

"""#Beginner Friendly with 3 primaries"""

#Shows beginner friendly operators who have 3 primary options
BeginnerFriendly[BeginnerFriendly["Primary3"] != "NO OPTION"]

"""#Beginner Friendly with 3 primaries and 2 secondaries"""

#Shows beginner friendly operators who have 3 primary and 2 secondary options

#Gets only the beginner friendly operators who have Primary 3 with a option (If they have a primary 3 they will have a primary 2)
FriendlyFullLoadout = BeginnerFriendly[BeginnerFriendly["Primary3"] != "NO OPTION"]

#Gets only the beginner friendly operators who have Secondary 2 with a option (They will alwyas have a secondary 1)
FriendlyFullLoadout = FriendlyFullLoadout[FriendlyFullLoadout["Secondary2"] != "NO OPTION"].reset_index(drop=True)

#displayrs FriendlyFullLoadout
FriendlyFullLoadout

"""#-------
#-------

#Finds all 'Kinda' beginner friendly Operators
"""

#Shows 'kinda' beginner friendly operators

#creates the new data frame
KindaBeginnerFriendly = df[df["Beginner Friendly"] == "Kinda"].reset_index(drop=True)


#displays the data frame
KindaBeginnerFriendly

"""#'Kinda' Beginner friendly with 3 primaries"""

#kinda beginner friendly who have 3 primaries

KindaBeginnerFriendly[KindaBeginnerFriendly["Primary3"] != "NO OPTION"]

"""#-------
#-------

#Finds All 'No' Beginner friendly Operators
"""

#creates the not beginner friendly operators data frame
NotBeginnerFriendly = df[df["Beginner Friendly"] == "No"].reset_index(drop=True)

#displays it
NotBeginnerFriendly

"""#'No' Beginner Friendly with 3 primaries"""

#shows the non beginner friendly operators with 3 primaries

NotBeginnerFriendly[NotBeginnerFriendly["Primary3"] != "NO OPTION"]

"""#-------
#-------

#Operators Organization
"""

#creates new data frame based off the amount of operators in a organization
df.loc[42:45,['Organization']] = 'GSG9'
Org = df['Organization'].value_counts()
Org = pd.DataFrame(Org)

#renames the columns since the index is organization
Org = Org.rename(columns={'Organization': 'Number of Operators'})

#sorts the values to make it look nicer
Org.sort_values('Number of Operators')

#displays it
Org

#creates a pie chart to show % the organization compares to the total
#explode to make it more readable
explode = (0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.25, 0.25)

#the pie plot
plot = Org.plot.pie(y="Number of Operators", figsize=(5, 5), explode = explode , ylabel="",rotatelabels = 180, autopct="%.f%%")

#removes legend
plot.get_legend().remove()

#puts space between the plot and title to not overlap some words
plt.title("Distribution of Organization", pad = 35)

#shows the amount of operators in each organization

#plots it
Org.plot.barh()

#the labels
plt.xlabel("Number of Operators")
plt.ylabel("Organization")

#displays it
plt.show()

"""#Visualization of Most common primaries"""

#variables that are the count without the value 'NO OPTION' for each primary
NoP1 = df[df["Primary1"] != "NO OPTION"]

NoP2 = df[df["Primary2"] != "NO OPTION"]

NoP3 = df[df["Primary3"] != "NO OPTION"]

#creates a countplot based off of primary 1 and how often values appear
sns.countplot(x = df['Primary1'], data = df['Primary1'] ,palette = "muted")

#creates the titles and labels
plt.title("First Primary Weapon Frequency")
plt.xlabel("Primary Name")
plt.ylabel("Count")

#rotates the names so they can be seen
plt.xticks(rotation = 90)

#sets the size
plt.gcf().set_size_inches(15,5)

#prints the text information about the 'NO OPTION' amount and total amount
print("Total number of 'Primary 1' that are not 'NO OPTION':",NoP1['Primary1'].value_counts().sum())
print("Total number of 'Primary 1':",df['Primary1'].value_counts().sum())

#creates a countplot based off of primary 2 and how often values appear
sns.countplot(x = df['Primary2'], data = df['Primary2'] ,palette = "muted")

#creates the titles and labels
plt.title("Second Primary Weapon Frequency")
plt.xlabel("Name")
plt.ylabel("Count")

#rotates the names so they can be seen
plt.xticks(rotation = 90)

#sets the size
plt.gcf().set_size_inches(15,5)

#prints the text information about the 'NO OPTION' amount and total amount
print("Total number of 'Primary 2' that are not 'NO OPTION':",NoP2['Primary2'].value_counts().sum())
print("Total number of 'Primary 2':",df['Primary2'].value_counts().sum())

#unfiltered, to show the 'NO OPTION'
#creates a countplot based off of primary 3 and how often values appear
sns.countplot(x = df['Primary3'], data = df['Primary3'] ,palette = "muted")

#creates the titles and labels
plt.title("Third Primary Weapon Frequency")
plt.xlabel("Name")
plt.ylabel("Count")

#rotates the names so they can be seen
plt.xticks(rotation = 90)

#sets the size
plt.gcf().set_size_inches(15,5)

#prints the text information about the 'NO OPTION' amount and total amount
print("Total number of 'Primary 3' that are not 'NO OPTION':",NoP3['Primary3'].value_counts().sum())
print("Total number of 'Primary 3':",df['Primary3'].value_counts().sum())

#filtered, Does not show 'NO OPTION'
#creates a countplot based off of primary 3 and how often values appear
sns.countplot(x = NoP3['Primary3'], data = NoP3['Primary3'] ,palette = "muted")

#creates the titles and labels
plt.title("Third Primary Weapon Frequency ( Filtered )")
plt.xlabel("Name")
plt.ylabel("Count")


#rotates the names so they can be seen
plt.xticks(rotation = 90)

#sets the size
plt.gcf().set_size_inches(15,5)

#prints the text information about the 'NO OPTION' amount and total amount
print("Total number of 'Primary 3' that are not 'NO OPTION':",NoP3['Primary3'].value_counts().sum())
print("Total number of 'Primary 3':",df['Primary3'].value_counts().sum())

"""#All Primaries"""

#creates a new data frame that contains only the primaries

#With 'NO OPTION'
pri = df["Primary1"]

#adds it to the end of the column
pri = pri.append(df["Primary2"])
pri = pri.append(df["Primary3"])

#makes it a data frame
pri = pd.DataFrame(pri)

#sets Primaries as axis
pri = pri.set_axis(['Primaries'], axis=1)

#Displays
pri

#creates a new data frame that contains only the primaries that is filtered

#without 'NO OPTION'/ filtered
pri2 = pri

#filters it
pri2 = pri2[pri2["Primaries"] != "NO OPTION"]

#Displays
pri2

#with 'no option'
sns.countplot(x = pri["Primaries"], data = pri ,palette = "muted")

#Creates the Title and Labels
plt.title("All Primaries Frequency")
plt.xlabel("Name")
plt.ylabel("Count")

#rotates the x values
plt.xticks(rotation = 90)

#set size
plt.gcf().set_size_inches(18,7)

#without 'no option'
sns.countplot(x = pri2["Primaries"], data = pri2 ,palette = "muted")

#Creates the Title and Labels
plt.title("All Primaries Frequency ( Filtered )")
plt.xlabel("Name")
plt.ylabel("Count")

#rotates the x values
plt.xticks(rotation = 90)

#set size
plt.gcf().set_size_inches(18,7)

"""#6 - Time Series (Not Applicable)

#7 - Conclusion and insight

**Key findings** - The data show above shows comparison of stats such as Armor, Speed and Difficulty. These stats can then be compared or filtered by other parts of the data such as the new column 'Beginner Friendly' , 'Organization' , and so on. While this code does not go over every single type of comparison/filtering available it goes over the main ones people may use with the intetnion of finding a character to play in the game.


**Challenges** - Some challenges I faced in this data was relating to filtering the words and getting them to display properly. Usually it was relating to minor mistakes I made such as adding the Primary1 - Primary3 together resulting in a single column but was a combitation of each string from that axis. I struggled with appening things proparly but figured it out. Along with that I struggled with choosing what should and shouldn't be compared/filterd since a lot of comparision/filtering is able to made. This caused some aspects of data that few may find useful to be left out while others may not even think about it. The hardest challeneg however was the heatmap and understanding the .map part I used to make the new column


**Recommendations** - I highly recommend that if you are willing to try almost evry comparison/filtering to do some more such as dataframes that show operators that have specific loadouts. An example would be they have "xyz" as a option for a primary and "abc" as a option ofr a secondary. While this information is not as useful as others some may still find it so. However, one thing this data lacks is each Operators ability. In future analysis I recommend finding either a similar data set with those abilities added or mannually adding them along with what type of ability it can be catagorized as (healing, mobility, distracton and ect) as seen fit. However this may cause issues due to some possiby being classified as one or more catogories so I recommend to only have 2 classifications per ability at most.
"""